### ISSUE TITLE
some navbar issues

### ISSUE THREAD

**Issue by gkht** [OfficeDev/Office-UI-Fabric#119] opened 2015-09-13 11:31 UTC
![navbar](https://cloud.githubusercontent.com/assets/14259276/9836450/fea8677c-5a1a-11e5-9d18-8e3477a283f5.jpg)
1, the upload menü item ''fall out"
2, when the drop down is open, you can select the menü items behind the drop down
(IE, version: 11.0.10011.0)

**Comment by ericthompson** [comment] 2015-09-14 00:34
Good catches - we'll look into this asap!

**Comment by aremes** [comment] 2015-09-17 09:50
One more: if i want to use the navbar without the search bar but with a dropdown (
"ContextualMenu", that is), it breaks on lines 419ff in fabric.js due to a missing null-check.
```
        // Close and blur the search box if it doesn't have text.
        if ($navBar.find('.ms-NavBar-item.ms-NavBar-item--search .ms-TextField-field').val().length === 0) {
          $('.ms-NavBar-item.ms-NavBar-item--search').removeClass('is-open').find('.ms-TextField-field').blur();
        }
```

changing these lines to

```
        // Close and blur the search box if it exists and doesn't have text.
        $searchBox = $navBar.find('.ms-NavBar-item.ms-NavBar-item--search .ms-TextField-field');
        if ($searchBox.length > 0 && $searchBox.val().length === 0) {
          $('.ms-NavBar-item.ms-NavBar-item--search').removeClass('is-open').find('.ms-TextField-field').blur();
        }
```

solves it. this also has to be done a few lines below at around line 464:

```
        // Close and blur the search box if it exists and doesn't have text.
        $searchBox = $navBar.find('.ms-NavBar-item.ms-NavBar-item--search .ms-TextField-field');
        if ($searchBox.length > 0 && $searchBox.val().length === 0) {
          $navBar.find('.ms-NavBar-item.ms-NavBar-item--search').removeClass('is-open').find('.ms-TextField-field').blur();
        }
```

Wouldn't you agree? or is it just me being an idiot assuming one might like to use the navbar without a search field? :)

**Comment by pbjorklund** [comment] 2015-10-02 16:39
I'm having the same issue and solved it the same was as @aremes

**Comment by aremes** [comment] 2015-10-02 16:44
@pbjorklund there's already a pull request under review by the office devs. :) as for the original issue, i couldnt reproduce.. any more info? if i can reproduce it, i'd be glad to attempt a fix.

**Comment by pbjorklund** [comment] 2015-10-02 16:45
If it's the same bug I think it just has to do with that a dropdown isn't closed when selecting another dropdown 
![image](https://cloud.githubusercontent.com/assets/290776/10252140/d0d55998-6935-11e5-9624-7d8d5353ad8b.png)

**Comment by jonahkirangi** [comment] 2015-10-16 19:48
The upload menu item "fall out" issue has been resolved in pull request https://github.com/OfficeDev/Office-UI-Fabric/pull/173. The layering issue has been resolved in pull request https://github.com/OfficeDev/Office-UI-Fabric/pull/175.

**Closed by jonahkirangi** 2015-10-16 19:48 UTC
Labels: bug, components, VSO

**Comment by pbjorklund** [comment] 2015-10-21 14:06
Is there a issue open for the search-field @jonahkirangi (I can't see an open one, might be resolved already as well)? I can create a new one and pull mine and @aremes comments together in that if there is none.

**Comment by ericthompson** [comment] 2015-10-21 17:37
We don't currently have an issue for the search field in the navbar. What are you seeing?
