### ISSUE TITLE
Panel Component, Release 2.2.0, Not Work: ms-PanelAction-close 

### ISSUE THREAD

**Issue by alexcandela007** [OfficeDev/Office-UI-Fabric#457] opened 2016-03-24 18:21 UTC

**Comment by mikewheaton** [comment] 2016-03-24 18:59
Can you provide some more details on this issue, or a link where we can see the problem?

**Comment by alexcandela007** [comment] 2016-03-24 22:15
the button that contains the class ms-PanelAction-close does not close the panel.

![panel](https://cloud.githubusercontent.com/assets/17366927/14032886/e20f26b2-f1e3-11e5-868b-6b670baea4ff.png)

**Comment by mikewheaton** [comment] 2016-03-25 00:17
Do you get any errors in the developer tools console? Were you able to use a button to open the panel?

**Comment by alexcandela007** [comment] 2016-03-25 00:47
the console does not display errors. And the previous version (Release 2.1.0) to operate normally

**Comment by mikewheaton** [comment] 2016-03-25 01:11
Hmm, very odd. Is there any chance you can share a link to that build? I've tested our panel here and it seems to be working fine: http://plnkr.co/edit/fdsALW?p=preview

**Comment by alexcandela007** [comment] 2016-03-25 01:33
It works correctly in your example and your files. I'm using the downloaded files the following link https://github.com/OfficeDev/Office-UI-Fabric/releases

fabric.components.css
fabric.components.min.css

fabric.css
fabric.min.css

jquery.fabric.js
jquery.fabric.min.js

Additional, download the update in Nuget, Microsoft Visual Studio.

In both cases it does not work, close the panel: "ms-PanelAction-close"

I will continue checking. Thank you for your help.

**Comment by alexcandela007** [comment] 2016-04-03 19:36
The following link can be visualized my problem with the close button panel

http://dev.office.com/fabric/components/panel

**Comment by mikewheaton** [comment] 2016-04-03 22:18
Please see my link above (http://plnkr.co/edit/fdsALW?p=preview) for an example of the Panel from Fabric 2.2.0 working correctly. If you could send us a link to the specific page you're having trouble with, or reproduce the issue on a site like Plunker, CodePen, or JSFiddle, we can take a look. I'll close this issue for now as I haven't been able to reproduce the problem.

**Closed by mikewheaton** 2016-04-03 22:18 UTC
Labels: question
