### ISSUE TITLE
ms-Panel-headerText looks terrible when line the wraps

### ISSUE THREAD

**Issue by gavinbarron** [OfficeDev/Office-UI-Fabric#333] opened 2016-02-08 18:07 UTC
The line height is pretty bad if the header text happens to wrap ![Bad line wrap](http://content.screencast.com/users/gavinbarron/folders/Snagit/media/facba89c-b948-43a8-bde6-8de8f8b4abec/02.04.2016-15.45.png)

**Comment by mikewheaton** [comment] 2016-02-08 20:57
Thanks for reporting this, @gavinbarron. It's actually a duplicate of #320 so I'll close it, but please keep submitting bugs as you see them.

**Closed by mikewheaton** 2016-02-08 20:57 UTC
