### ISSUE TITLE
Document how to open/close a dialog

### ISSUE THREAD

**Issue by anasnakawa** [OfficeDev/Office-UI-Fabric#110] opened 2015-09-09 08:34 UTC
I cannot seem to find those [two javascript files](https://github.com/OfficeDev/Office-UI-Fabric/blob/master/dist/samples/Components/Dialog/index.html#L14-L15) ( `Jquery.Dialog.js` & `Dialog.js` ) that are required for the dialog to be available anywhere in the project

once the build is done, I believe they should exist in [this directory](https://github.com/OfficeDev/Office-UI-Fabric/tree/master/dist/samples/Components/Dialog)

**Comment by Jahnp** [comment] 2015-09-09 16:13
Hey @anasnakawa , this is because of https://github.com/OfficeDev/Office-UI-Fabric/issues/67. Basically, the template used for component demo HTML pages always has a reference to <Component>.js and Jquery.<Component>.js, even if those don't exist. We're working on a fix for this that should be ready soon; I'll close the issue for now since the work for it is already being tracked. Thanks for catching this!

**Comment by anasnakawa** [comment] 2015-09-09 16:18
thanks, 

but beside that demo pages issue,
the `Dialog` javascript files mentioned above are not available anywhere in the repository.

**Comment by Jahnp** [comment] 2015-09-09 16:24
Ah, I see, I must have misunderstood. There actually have never been JS for Dialog--the references above are a bit misleading in that sense--but would it be fair to say the issue is that there *should* be? I could see us including JS to demo how to open/close specific dialogs.

**Comment by anasnakawa** [comment] 2015-09-09 16:38
> the references above are a bit misleading in that sense

yes they are, and they are not the only thing misleading here, 
also the example provided in the same demo page for the dialog is confusing me,
like when I tried to include the whole Fabric UI javascript library,
I cannot seem to find any definition for the following:

```js
fabric['Dialog']; // undefined
$.fn.Dialog; // undefined
```
Is there any part that I am missing here ?

Thanks.

**Comment by Jahnp** [comment] 2015-09-09 16:58
Nope, I think you've got it. This sounds like what the issue in https://github.com/OfficeDev/Office-UI-Fabric/issues/67 is describing. The problem is that those demo files are generated automatically from a [template](https://github.com/OfficeDev/Office-UI-Fabric/blob/master/src/templates/individual-component-example.html), and that template includes hard-coded references to component scripts, *even if those files don't exist*, since not every component has or requires JS to work. You'll notice the same issue for List, ListItem, Callout, and a few others in addition to Dialog. 

We know this is pretty confusing, so we'll make sure to update the build & template to only include references to JS files if they exist. 

Does this help?

**Comment by digglek** [comment] 2015-09-22 09:49
Is it possible you are able to proivide an example of how to open/close a dialog? 

Regards

**Comment by robledosm** [comment] 2015-12-15 23:40
Could you please provide an example of how to open/close a dialog?

**Comment by ericthompson** [comment] 2015-12-18 17:33
Reopening so we can track it.

**Comment by mikewheaton** [comment] 2016-01-26 02:45
The Dialog has an overlay, but we don't provide sample JavaScript to show how the dialog can be opened and dismissed. This should be added so that we can help developers use it, and to document the animations.

**Comment by mikewheaton** [comment] 2016-01-26 16:47
Turns out there is a demonstration of this (screenshot below) in the samples that are distributed with Fabric. If you [download Fabric](https://github.com/OfficeDev/Office-UI-Fabric/releases/latest/) you'll find it under `dist/samples/Components/Dialog/index.html`.

Can we get these examples working on the [dialog page](http://dev.office.com/fabric/components/dialog) of our main documentation site?

![image](https://cloud.githubusercontent.com/assets/1382445/12587381/f2cd854c-c408-11e5-81f5-ff561d5f8a19.png)

**Comment by mikewheaton** [comment] 2016-02-08 02:32
This should be fixed when we update the documentation site to pull the latest components from Fabric. Leaving this issue open to ensure it gets fixed.

**Comment by mikewheaton** [comment] 2016-03-09 00:49
It's working on the docs site now: http://dev.office.com/fabric/components/dialog

You can click the JS tab to see the Javascript in use to open and close the dialog.

**Closed by mikewheaton** 2016-03-09 00:49 UTC
Labels: documentation, VSTS
