### ISSUE TITLE
Certain component styles not in CDN?

### ISSUE THREAD

**Issue by manndave** [OfficeDev/Office-UI-Fabric#373] opened 2016-02-21 20:22 UTC
I tried pulling the fabric.components.css from "http://appsforoffice.microsoft.com/fabric/2.0/fabric.components.css" and "http://appsforoffice.microsoft.com/fabric/2.0.1/fabric.components.css" and I don't see the MessageBanner or ProgressIndicator classes/styles in there or in the minified versions.  I also checked the regular fabric.css.  They're in my cloned repo and in the samples, just don't seem to be in the CDN.  Am I missing something?  

Thanks,

Dave

**Comment by mikewheaton** [comment] 2016-02-21 22:09
Confirmed. Fabric 2.0.1 (both the [CDN copy](http://appsforoffice.microsoft.com/fabric/2.0.1/fabric.components.css), [direct download](https://github.com/OfficeDev/Office-UI-Fabric/releases/tag/2.0.1), and Bower package) are missing the styles for MessageBanner and ProgressIndicator. They're in the component folders (e.g. components/MessageBanner/MessageBanner.css) but were not built into the main components' CSS file.

When I do a Gulp build locally they're included. Looks like something went wrong with the build before deploying 2.0.1? I don't know why this would happen.

**Comment by manndave** [comment] 2016-02-21 23:03
FWIW, they're not in 2.0, either.

**Comment by Jahnp** [comment] 2016-02-22 02:29
These were each fixed in #326 and #335, which were merged after the 2.0.1 release. They will be included in the 2.1.0 release, however.

**Closed** 2016-02-22 02:30 UTC
Labels: bug, build-system
