### ISSUE TITLE
PeoplePicker: issues, questions

### ISSUE THREAD

**Issue by s-KaiNet** [OfficeDev/office-ui-fabric#507] opened 2016-04-23 21:21 UTC
I'm working on people picker component in ng- repository and have some questions, may be some of them are issues\bugs, may be not. All for version 2.4.1.   
Please, take a look. Sorry if it's a bit messy.   

1. [demo web site] and [repo: dist\samples\]: when clicking on "Search Contacts & Directory"  there is no spinner animation (but code for animation exists)
2. [demo web site] and [repo: dist\samples\]: not working click by Additional data (`chevronsDown` icon in search results), but code for click event exists
3. [markup]: `ms-PeoplePicker-searchMore js-searchMore` component uses `<div tabindex="0" role="button" class="ms-PeoplePicker-searchMoreBtn">` in all scenarios, but the very first one in demo uses `<button class="ms-PeoplePicker-searchMoreBtn">` button instead of div - inconsistency 
4. [common]: what is the purpose for delete button under search results? I assumes that's something you are getting from server\whatever and it doesn't make sense to delete it. 
5. [common]: are there any special styles for disabled state? 
6. [compact mode]: people picker in compact mode have styling issue in disconnected scenario
7. [memberList]: how to show visual animation when searching in memberList mode? It doesn't have "Search more"  footer
8. [memberList]: memberList demo missing in demo site

**Comment by mikewheaton** [comment] 2016-04-24 21:41
Thanks for bringing all of these bugs to our attention, @s-KaiNet. We're currently doing a full scrub and rewrite of the components with Handlebars templates and TypeScript, and we can make sure these issues are resolved before releasing 3.0.0.

**Comment by Jahnp** [comment] 2016-07-06 20:31
Hey @s-KaiNet, sorry for the delay. I know it's been awhile, but I'd like to address each of your issues:

1. This is a duplicate of #638, which we are targeting to have fixed in 3.0.
2. This functionality has been deprecated from the PeoplePicker and will be removed in 3.0.
3. Good catch--we should be consistent here. This will be fixed in 3.0.
4. We'll be providing better usage guidelines for affordances such as this with the 3.0 release. While I can't guarantee that this specific functionality will be addressed, know that it's a high priority for us to address moving forward.
5. To be clear, do you mean a disabled state for the TextField that the PeoplePicker is invoked from? If so, that should follow that same pattern as TextField. Since that doesn't exist right now we'll open a separate bug to track those styles.
6. See the answer to question 1--this should be fixed in 3.0.
7. The MemberList variant of the PeoplePicker has been deprecated in 3.0 in favor of the FacePile component.
8. Same as 7--MemberList has been deprecated.

Thanks again so much for your feedback here!

**Closed by Jahnp** 2016-07-06 20:31 UTC
Labels: bug, documentation, VSTS
